package view;

import controller.ProductController;
import controller.ValidationController;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ProductRecord;
import util.SignificantRecord;

public class SuperAdminRecords extends javax.swing.JFrame {

    ValidationController validationController = new ValidationController();
    ProductController productController = new ProductController();
    List<ProductRecord> productRecord;

    /**
     * Creates new form Admin
     */
    public SuperAdminRecords() throws Exception {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        pnlViewProduct.setVisible(true);
        viewProduct();

    }

    public SuperAdminRecords(int adminID) throws IOException, Exception {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        pnlViewProduct.setVisible(true);
        viewProduct();
    }

    // load and view product data
    public void viewProduct() throws IOException, Exception {
        List<SignificantRecord> allSignificantRecord  = productController.viewAllUniqueProductCode();

        // set table column
        String columns[] = { "Product Unique Code", "Harvest Date", "Farm Location", "Production Date", "Production Location", "Storage Date", "Storage Location", "Expiry Date", "Product ID" };
        
        DefaultTableModel defaultTableModel = (DefaultTableModel)tblProduct.getModel();
        defaultTableModel.setColumnIdentifiers(columns);
                
        tblProduct.setModel(defaultTableModel);
        defaultTableModel.setRowCount( 0);
        
        // loop data into table
        for (SignificantRecord record :  allSignificantRecord) {
            String[] data = {
                record.productUniqueCode(),
                record.harvestDate(),
                record.farmLocation(),
                record.productionDate(),
                record.productionLocation(),
                record.storageDate(),
                record.storageLocation(),
                record.expiryDate(),
                record.productTypeID()
            };
            
            defaultTableModel.addRow(data);
        }
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlTopNav = new javax.swing.JPanel();
        lblProductOriginTracer = new javax.swing.JLabel();
        pnlViewProduct = new javax.swing.JPanel();
        btnReturn = new javax.swing.JButton();
        scrpanProduct = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Origin Tracer - Super Admin");

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainer.setPreferredSize(new java.awt.Dimension(1300, 800));

        pnlTopNav.setBackground(new java.awt.Color(245, 245, 245));
        pnlTopNav.setPreferredSize(new java.awt.Dimension(1300, 50));

        lblProductOriginTracer.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblProductOriginTracer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductOriginTracer.setText("Product Origin Tracer - Product Type");

        javax.swing.GroupLayout pnlTopNavLayout = new javax.swing.GroupLayout(pnlTopNav);
        pnlTopNav.setLayout(pnlTopNavLayout);
        pnlTopNavLayout.setHorizontalGroup(
            pnlTopNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopNavLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(lblProductOriginTracer, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
        );
        pnlTopNavLayout.setVerticalGroup(
            pnlTopNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlTopNavLayout.createSequentialGroup()
                .addComponent(lblProductOriginTracer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        pnlViewProduct.setBackground(new java.awt.Color(255, 255, 255));
        pnlViewProduct.setPreferredSize(new java.awt.Dimension(1300, 700));

        btnReturn.setBackground(new java.awt.Color(73, 161, 236));
        btnReturn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Back");
        btnReturn.setBorder(null);
        btnReturn.setOpaque(true);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        tblProduct.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        )

        { public boolean isCellEditable(int row, int column) { return false; }});
    scrpanProduct.setViewportView(tblProduct);

    javax.swing.GroupLayout pnlViewProductLayout = new javax.swing.GroupLayout(pnlViewProduct);
    pnlViewProduct.setLayout(pnlViewProductLayout);
    pnlViewProductLayout.setHorizontalGroup(
        pnlViewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlViewProductLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(pnlViewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrpanProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 1224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(357, Short.MAX_VALUE))
    );
    pnlViewProductLayout.setVerticalGroup(
        pnlViewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlViewProductLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(20, 20, 20)
            .addComponent(scrpanProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(126, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
    pnlContainer.setLayout(pnlContainerLayout);
    pnlContainerLayout.setHorizontalGroup(
        pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pnlTopNav, javax.swing.GroupLayout.DEFAULT_SIZE, 1601, Short.MAX_VALUE)
        .addComponent(pnlViewProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1601, Short.MAX_VALUE)
    );
    pnlContainerLayout.setVerticalGroup(
        pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlContainerLayout.createSequentialGroup()
            .addComponent(pnlTopNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pnlViewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1601, Short.MAX_VALUE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // add product button
    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperAdminRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperAdminRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperAdminRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperAdminRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SuperAdminRecords().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(SuperAdminRecords.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel lblProductOriginTracer;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlTopNav;
    private javax.swing.JPanel pnlViewProduct;
    private javax.swing.JScrollPane scrpanProduct;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables
}
